### ISSUE TITLE
Alfresco error when using data volume for "/alfresco/alf_data"

### ISSUE THREAD

**Issue by DamienMure** [gui81/docker-alfresco#7]
Hi.
When I run this command to start a brand new alfresco :
`docker run --name alfresco -it --rm -v /host/alfresco/content:/content -v /host/alfresco/data:/alfresco/alf_data gui81/alfresco`

Alfresco is able to start, but I can't log in and I get the following error:
`Your authentication details have not been recognized or Alfresco may not be available at this time.`

In the log file "/alfresco/tomcat/logs/catalina.out" I get this error (and many others):
`SEVERE: Failed to load keystore type JCEKS with path /alfresco/alf_data/keystore/ssl.keystore due to /alfresco/alf_data/keystore/ssl.keystore (No such file or directory)`

The data volume mounted from the docker host is empty. So, the directory /alfresco/alf_data is empty too: no keystore to load.

During the installation process triggered by the Dockerfile, alfresco put several mandatory stuffs into /alfresco/alf_data.
Mounting an empty data volume in place of the /alfresco/alf_data make alfresco unable to work properly.
Can we save the alf_data at the end of the dockerfile and restore it (if it doesn't exist) during the init.sh ? So the data volume would be populated using the mandatory data at the first run of the container ?

Regards.

**Comment by thecortex** [comment]
Hello,

I am having the very same issue when I run;

docker run --name='alfresco' -d -p 8080:8080 \
	-v $HOME/alfresco_volumes/alf_data:/alfresco/alf_data \
	-v  $HOME/alfresco_volumes/tomcat_logs:/alfresco/tomcat/logs  \
	-v $HOME/alfresco_volumes/content:/content \
	gui81/alfresco

SEVERE: Failed to initialize end point associated with ProtocolHandler ["http-bio-8443"]
java.io.FileNotFoundException: /alfresco/alf_data/keystore/ssl.keystore (No such file or directory)

Should I run the keytool inside the docker machine to generate the certificate?

http://docs.alfresco.com/4.0/tasks/generate-repo-ssl-keystore.html
http://docs.alfresco.com/4.0/tasks/generate-repo-ca-key.html

Are you planning on automating this feature?

Regards,
Mustafa Qamar-ud-Din

**Comment by thecortex** [comment]
Hello,

I received the following error after adding the keystore certifcates;

SEVERE: Error listenerStart
May 28, 2016 4:58:11 AM org.apache.catalina.core.StandardContext startInternal

ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-39] Tracking failed
 java.net.ConnectException: Connection refused

Thanks for your help in advance.

**Comment by DamienMure** [comment]
I'm now using https://github.com/disaster37/rancher-alfresco, which : 
- run alfresco 5.1 .(and I really need this)
- includes sames stuffs like ones in my previous pull resquests
- save/restore alf_data at first startup to prevent alfresco from the "/alfresco/alf_data/keystore/ssl.keystore (No such file or directory)" error.

Regards.

**Comment by thecortex** [comment]
Dear Damien,

Thank you for sharing it with me, but it works only on Rancher stack?!

Regards,

**Comment by thecortex** [comment]
Dear Damien,

I have run the following commands

**First I ran a container:**
$docker run --name='alfresco' -d -p 8080:8080 \
	-v $HOME/alfresco_volumes/alf_data:/alfresco/alf_data \
	-v  $HOME/alfresco_volumes/tomcat_logs:/alfresco/tomcat/logs  \
	-v $HOME/alfresco_volumes/content:/content \
	gui81/alfresco

**Then I copied the files from container to my host**
$ docker cp ba79858445a641535f1863b886706c2e0b2a4575aeb7db1d0c419a49a5e56e3e:/alfresco/alf_data $HOME/alfresco_copy/alf_data

$ docker cp ba79858445a641535f1863b886706c2e0b2a4575aeb7db1d0c419a49a5e56e3e:/content $HOME/alfresco_copy/content

**Then I removed the previous container and run a fresh copy using the ssl keys from the previous one**
$  docker run --name='alfresco' -d -p 8080:8080 \ 
        -v $HOME/alfresco_copy/alf_data:/alfresco/alf_data \
        -v  $HOME/alfresco_copy/tomcat_logs:/alfresco/tomcat/logs  \
        -v $HOME/alfresco_copy/content:/content \
        gui81/alfresco

I believe I made a mistake by removing the container, but  what do you suggest, since I am still getting the following error:

SEVERE: Failed to initialize end point associated with ProtocolHandler ["http-bio-8443"]
java.io.IOException: Keystore was tampered with, or password was incorrect

Regards,

**Comment by DamienMure** [comment]
Hi.
I do not have much time, so quickly:
- Yes, I'm using the other container with rancher. But you can run it as is, outside any rancher architecture (as any other container.).. You have examples in the README.

- If you really want to do it by yourself : at your first step do not use any "-v". If you use "-v $HOME/alfresco_volumes/alf_data:/alfresco/alf_data", you mount an empty directory into your alfresco...So during "docker cp", you also copy an empty directory.
If you remove "-v", you will be able to copy to original content of alf_data to you $HOME. Then you can use "-v" during the last step to mount it into your brand new alfresco.

- But the right way to do this is by writing your own Dockerfile:
-- FROM "gui81/docker-alfresco"
-- move the alf_data to /somewhereelse
-- write and add you own ENTRYPOINT.

In this custom entrypoint, you check if alf_data is here. If not, you rename "/somewhereelse" to alf_data. If yes, do nothing. Then, call for the original ENTRYPOINT(/alfresco/init.sh).

Regards.

**Comment by thecortex** [comment]
Dear Damien,

Thank you for your hints;

I've written a blog about this experience, and I am looking forward to your feedback.

https://mustafamahrous.wordpress.com/2016/05/19/how-to-deploy-alfresco-using-docker-in-3-minutes/

With best regards,

**Comment by DamienMure** [comment]
I would like you to remove my name from your blog and just keep a link to this thread.

I told you how to bypass the issue, but it's not something that should be done for a production environment for many reasons I won't explain here.
You should tell on your blog that is for a ProofOfConcept, not to be used in Production.
(btw, many interesting things to read here to tune alfresco's config/arch: https://docs.alfresco.com/4.2/concepts/master-gs-intro.html)

This thread is dedicated to the issue, so I won't write any more about something else.

Thx.

**Comment by thecortex** [comment]
Dear Damien,

- I have removed your name.
- I left a link to this thread.
- I added a note that this was only a proof of concept.

Thank you for your help.

P.S. If you may advise what should be used in production on a separate thread if possible, I'd be grateful.

**Comment by gui81** [comment]
I have updated this to bootstrap the data on initial install if you are mounting volumes.  Try out the latest version and see if that works better for you.

Yes, this is less than ideal for production use.  I don't believe Alfresco is exactly well suited for running in a container in the first place, since it requires several services to be running.  It can be done, but a better deployment would not use supervisor and instead run the Docker recommended way, i.e. one service per container.  There are many other considerations as well, depending on your definition of production.  Nevertheless, we do run with this version in a lab setting to share documents on a very small scale instead of passing DVDs around with data.
